#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md"]

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

# the base hostname & protocol for your site
url: "https://jackalandhydemusic.com"

####################################
######   Optional Features    ######
####################################
smooth-scroll: true

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!

sass:
  sass_dir: css


jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Jackal and Hyde Music
# Website language
lang: en-US
# Header Title
header-title: <strong>Electromagnetic</strong>
# Header Tagline
header-tagline: NEW SINGLE

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Buy Now
  url: https://jackalandhyde.bandcamp.com/track/electromagnetic

# Secondary Buttons
header-secondary-button:
  title: Listen
  url: https://jackalandhyde.bandcamp.com/track/electromagnetic

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: starriew@gmail.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://www.patreon.com/jackalandhyde
banner-link2: https://jackalandhyde.bandcamp.com

####################################
######  Global Social Links   ######
####################################
youtube: 'https://www.youtube.com/channel/UC3ixZnMnCb_lMJukcDDQFiQ'
facebook: 'https://www.facebook.com/jackalandhyde/'
instagram: 'https://www.instagram.com/jackalandhydemusic/'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: jackalhyde_about_image.jpeg
  author-name: Jackal and Hyde News
  author-tagline:
  author-info: Keeping you up-to-date on the latest Jackal and Hyde news.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Sera Google Map
map-text-location: Los Angeles, United States
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Jackal and Hyde - Dominance Electricity (Leipzig, Germany), Risen United (Los Angeles, USA)
about-description: Scott Weiser, (AKA Jackal and Hyde) is responsible for some of the most head strong electrocore bass-bangers such as Dark Star, Go Bang, Beyond, This is the Sound of Underground and Bad Robot. Besides his original work, Jackal & Hyde's sound has been requested for multiple remix productions including Rabbit in the Moon, Kid Rock, Limp Bizkit, Gwen Stefani, Newcleus, Mindless Self Indulgence, Carl Finlow, Love & Rockets and Genitorturers among others. In 2020, he continues the mission to create the perfect blend of relentless intelligent club power along with futuristic darkness to make his brand of sci-fi-esque electro music called electrocore. <br /><br />Jackal and Hyde live shows are eclectic full frontal sonic assaults which appeal to a wide variety of fans from EDM club kids, ravers and break dancers, to goths, gravers and industrial heads alike. For the last decade he has played shows with a wide variety of groups from The Prodigy, Bassnectar and Stanton Warriors, to Rabbit in the Moon, Combichrist and Kraftwerk (Karl Bartos) at venues all across the United States and abroad. Always be prepared for an Earth shaking set from this master of tear out electro.


#####################################
#############  Features  ############
#####################################
features-title: Features
features-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante.

#
# Features
#
features:

# Feature
- title: Clean & Unique Design
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-vector

# Feature
- title: Professional Support
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-help2

# Feature
- title: Pixel Perfect
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-airplay


#####################################
############  Portfolio  ############
#####################################
portfolio-title: Buy Music
portfolio-description: Purchase high quality downloads for Jackal and Hyde's music on Bandcamp.

#
# Portfolio Grid
#
portfolio-categories: [Jackal and Hyde, Evan Gamble Lewis, Omar Santana, Code Rising, Otto Von Schirach, Carl Finlow, Genitorturers]
portfolio:

# Portfolio Item
- title: <span class="thin">Electromagnetic E.P.</span>
  categories: [Jackal and Hyde]
  image: img-05.jpg
  url: 'https://jackalandhyde.bandcamp.com/album/electromagnetic-e-p'

# Portfolio Item
- title: <span class="thin">COGITO ERGO SUM</span>
  categories: [Jackal and Hyde]
  image: img-01.png
  url: 'https://jackalandhyde.bandcamp.com/track/cogito-ergo-sum'

# Portfolio Item
- title: <span class="thin">Sound of Underground</span> (Remaster)
  categories: [Jackal and Hyde]
  image: img-07.jpg
  url: 'https://jackalandhyde.bandcamp.com/track/sound-of-underground-remaster'

# Portfolio Item
- title: <span class="thin">Anywhere in the Galaxy</span>
  categories: [Jackal and Hyde, Omar Santana, Code Rising, Genitorturers]
  image: img-04.jpg
  url: 'https://jackalandhyde.bandcamp.com/album/anywhere-in-the-galaxy-e-p-omar-santana-code-rising-genitorturers'

# Portfolio Item
- title: <span class="thin">Super Meng</span>
  categories: [Jackal and Hyde, Otto Von Schirach]
  image: img-06.jpg
  url: 'https://jackalandhyde.bandcamp.com/track/supermeng-3'

# Portfolio Item
- title: <span class="thin">Carl Finlow - Anomoly</span> (Jackal and Hyde Remix)
  categories: [Jackal and Hyde, Carl Finlow]
  image: img-02.png
  url: 'https://jackalandhyde.bandcamp.com/track/anomaly'

# Portfolio Item
- title: See Europa
  categories: [Jackal and Hyde]
  image: img-03.jpg
  url: 'https://jackalandhyde.bandcamp.com/track/see-europa'

- title: Newcleus - JAM ON IT (JACKAL AND HYDE'S ODE TO THE OLD SCHOOL REMIX)
  categories: [Jackal and Hyde]
  image: img-12.jpg
  url: 'https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.beatport.com%2Frelease%2Fjam-on-it-jackal-and-hydes-ode-to-the-old-school-remix%2F2553918%3Ffbclid%3DIwAR1Q27aL15OCimxPC3E-lw208LPTbDM7alW16ULPim6f8SLhbRexHq2AOkU&h=AT0Ps1jOllKXOQjJ40flpCHwo6lDQ6Uz1MDFdmA1N7j4HEOp2bWUnPsDAgj3_FsnaInahCydVWzK-eZfzG05LM504X3p8mUVD45KO8xyh0T6ikjKWPy2tD-YqndsrhLCGKEo72bi'

# Portfolio Item
- title: Candy Painted
  categories: [Jackal and Hyde]
  image: img-10.jpg
  url: 'https://jackalandhyde.bandcamp.com/album/candy-painted'

# Portfolio Item
- title: Beyond (Evan Gamble Lewis Remix)
  categories: [Jackal and Hyde , Evan Gamble Lewis]
  image: img-11.jpg
  url: 'https://jackalandhyde.bandcamp.com/track/beyond-evan-gamble-lewis-remix'

# Portfolio Item
- title: Bad Robot
  categories: [Jackal and Hyde]
  image: img-08.jpg
  url: 'https://jackalandhyde.bandcamp.com/album/bad-robot'

# Portfolio Item
- title: You're Like a Drug E.P. (Jackal and Hyde vs. Evan Gamble Lewis )
  categories: [Jackal and Hyde, Evan Gamble Lewis]
  image: img-09.jpg
  url: 'https://jackalandhyde.bandcamp.com/album/youre-like-a-drug-ep'
# Portfolio Item

#####################################
##########  Core Features  ##########
#####################################
core-title: Social Media
core-description: Follow Jackal and Hyde on social media.

#
# Core Features Left
#
core-features-left:

# Feature
- name: Bandcamp
  description: Buy Jackal and Hyde Music.
  icon: fi flaticon-instagram
  url: https://jackalandhyde.bandcamp.com

# Feature
- name: Discogs
  description: View the discography.
  icon: pe-7s-album
  url: https://www.discogs.com/artist/35393-Scott-Weiser?filter_anv=0&type=Credits

# Feature
- name: Instagram
  description: Stay up to date on Instagram.
  icon: fi flaticon-instagram
  url: https://www.instagram.com/jackalandhydemusic/

# Feature
- name: Facebook
  description: Follow Jackal and Hyde on Facebook.
  icon: fi flaticon-facebook
  url: https://www.facebook.com/jackalandhyde/?ref=br_rs

#
# Core Features Right
#
core-features-right:

# Feature
- name: YouTube
  description: Subscribe to the Listen to music.
  icon: fi flaticon-youtube
  url: https://www.youtube.com/channel/UC3ixZnMnCb_lMJukcDDQFiQ

# Feature
- name: Mailing List
  description: Sign up for the Jackal and Hyde email list.
  icon: pe-7s-mail
  url: mailto:info@jackalandhydemusic.com

# Feature
- name: Spotify
  description: Stream Jackal and Hyde Music.
  icon: pe-7s-musiclist
  url: https://open.spotify.com/artist/4a3Z4srAHtEhr1aEdB1SAi

# Feature
- name: Resident Advisor
  description: Keep up to date with upcoming shows and purchase tickets.
  icon: pe-7s-music
  url: https://ra.co/dj/jackalhyde


#####################################
########### Testimonials ############
#####################################
testimonials-title: Notable Quotes
testimonials-description:

#
# Testimonials
#
testimonials:

# Client
- name: Zardonic
  url: https://zardonic.net/
  url-text: Zardonic.net
  avatar: avatar-01.jpg
  cite: "Beautifully well crafted electro. Dark like no other in the electronic scene today."
  logo-img: videohive.png

# Client
- name: DJ Qbert (DMC Champion &num;1 Dj in the World)
  url: https://www.facebook.com/skratchdjqbert/
  url-text: DJ Qbert Facebook
  avatar: avatar-02.jpg
  cite: "Love Jackal and Hyde! I played his new track on our Turntable TV Livestream and a guy jumped up in front of the camera and tore it up popping and locking! Everyone went haywire! Jackal & Hyde is the best!"
  logo-img: videohive.png

# Client
- name: DJ Icey
  url: https://www.djicey.com/
  url-text: djicey.com/
  avatar: avatar-03.jpg
  cite: "What Wiwek is to Jungle Terror, Jackal & Hyde is to electro terror! Dark brooding bass music delivered from another solar system."
  logo-img: videohive.png

# Client
- name: Omar Santana
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-04.jpg
  cite: "The King of hard electro-core is back with a devastating and powerful bass track. Jackal and Hyde has proven once again that he is the undisputed king of this genre. This track will definitely cause a ruckus! Great work!"
  logo-img: audiojungle.png

# Client
- name: AK1200
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-05.jpg
  cite:  "If you really want to know what electro music is, go check out the new Jackal and Hyde. This is the music that shaped an era, and was instrumental in the success of breakdancing and dance battles throughout the world. If this is the future of proper electro, I can't wait to see what comes of it. Jackal and Hyde is again leading the way for electro and a revolution seems imminent."
  logo-img: audiojungle.png

# Client
- name: Dave Clarke
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-06.jpg
  cite: "The biggest f***ing bass you are ever going to experience."
  logo-img: audiojungle.png

# Client
- name: John B
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-07.jpg
  cite: This new Jackal and Hyde wax gets my RobotroniK seal of approval!
  logo-img: audiojungle.png

# Client
- name: Egyptian Lover
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-08.jpg
  cite: That new Jackal & Hyde song Bad Robot? Yea, the World must cop that… The World must cop the Bad Robot!”
  logo-img: audiojungle.png

#####################################
############# Our Blog ##############
#####################################
blog-title: News
blog-description: Stay up-to-date with the latest news about releases, live shows and anything else!


#####################################
############### Team ################
#####################################
team-title: Sponsors
team-description: Please support our sponsors.

#
# Team Members
#
team:

# Team Member
- name: Drone
  tagline: Artist
  avatar: drone.jpg
  url: https://droneart.etsy.com

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: 'https://www.facebook.com/dronefury'
  twitter: '#'
  instagram: 'https://www.instagram.com/the.art.of.drone/'


# Team Member
- name: Goldbaby
  tagline: Audio Mastermind
  avatar: goldbaby.jpg
  url: https://www.goldbaby.co.nz/

  # Social Links
  youtube: '#'
  facebook: 'https://www.facebook.com/goldbabysamples'
  twitter: '#'
  instagram: '#'
  vimeo: '#'

# Team Member
- name: Shady Teez
  tagline: Fashionista
  avatar: shadyteez.jpg
  url: https://www.shadyteez.com/

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: 'https://www.facebook.com/SHADYTEEZ'
  twitter: '#'
  instagram: 'https://www.instagram.com/shadygroupinc/'
  vimeo: '#'


# Team Member
- name: Kazrog
  tagline: Audio Plug-ins
  avatar: kazrog.jpg
  url: https://kazrog.com/

# Social Links
  youtube: 'https://www.youtube.com/user/Recabinet'
  pinterest: '#'
  facebook: 'https://www.facebook.com/kazrogplugins'
  twitter: 'https://twitter.com/kazrog?lang=en'
  instagram: 'https://www.instagram.com/kazrog/'
  vimeo: '#'



#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Studio Services
pricing-description: Scott Weiser is available for studio work offering a variety of services. Email <a href = "mailto:info@jackalandhydemusic.com">info@jackalandhydemusic.com</a> to discuss your project.

#
# Plan Personal
#
plan-personal-price: $50.00
plan-personal-offer-1-title: Package deals are available
plan-personal-offer-1-info: Email for package rates
plan-personal-url: mailto:info@jackalandhydemusic.com

#
# Plan Business
#
plan-business-price: $500.00
plan-business-offer-1-title: Mastered at professional quality
plan-business-offer-1-info:
plan-business-offer-2-title: Stems included
plan-business-offer-2-info:
plan-business-url: mailto:info@jackalandhydemusic.com

#
# Plan Ultimate
#
plan-ultimate-price: From $1500.00
plan-ultimate-offer-1-title: Remixed
plan-ultimate-offer-1-info: My remix of your song mixed
plan-ultimate-offer-2-title: Mixed down and mastered.
plan-ultimate-offer-2-info: Mixing and mastering included ($1,500 minimum, prices on remixes are project dependent)
plan-ultimate-url: mailto:info@jackalandhydemusic.com


#
# Plan Ultimate
#
plan-production-price: From $2500.00
plan-production-offer-1-title: Produced
plan-production-offer-1-info: You send me your song with every single track stemmed out and I produce it to professional quality and and bring the song up to its maximum potential
plan-production-offer-2-title: Mixed and mastered
plan-production-offer-2-info: Mix it down and deliver it back to you mastered
plan-production-url: mailto:info@jackalandhydemusic.com



#####################################
############   Contact   ############
#####################################
contact-title: Contact
contact-description: Interested in booking Jackal and Hyde for a live show? Have a question about something or just want to say hello? Send an email through the form below or contact <a href"mailto:info@jackalandhydemusic.com">info@jackalandhydemusic.com</a>.


#####################################
#############   Footer   ############
#####################################
footer-description: Jackal and Hyde Music is brought to you by Jackal and Hyde and Equinox Multimedia
footer-copyright-text: Equinox Multimedia
footer-copyright-url: http://www.equinoxmultimedia.com
footer-copyright-year: 2021
