#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md"]

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

# the base hostname & protocol for your site
url: "http://localhost:3000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: true

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!

sass:
  sass_dir: css


jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Jackal and Hyde Music
# Website language
lang: en-US
# Header Title
header-title: <strong>Cogito Ergo Sum</strong>
# Header Tagline
headter-tagline: New Single

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Buy Now
  url: https://jackalandhyde.bandcamp.com/track/cogito-ergo-sum

# Secondary Buttons
header-secondary-button:
  title: Listen
  url: https://jackalandhyde.bandcamp.com/track/cogito-ergo-sum

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: starriew@gmail.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://jackalandhyde.bandcamp.com

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: 'https://www.facebook.com/jackalandhyde/'
twitter: '#'
instagram: 'https://www.instagram.com/jackalandhydemusic/'
vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: Scott Weiser
  author-tagline: Blog Author
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Sera Google Map
map-text-location: Los Angeles, United States
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Jackal and Hyde - Dominance Electricity (Leipzig, Germany), Risen United (Los Angeles, USA)
about-description: Scott Weiser, (AKA Jackal and Hyde) is responsible for some of the most head strong electrocore bass-bangers such as Dark Star, Go Bang, Beyond, This is the Sound of Underground and Bad Robot. Besides his original work, Jackal & Hyde's sound has been requested for multiple remix productions including Rabbit in the Moon, Kid Rock, Limp Bizkit, Newcleus, Mindless Self Indulgence, Carl Finlow, Love & Rockets and Genitorturers among others. In 2020, he continues the mission to create the perfect blend of relentless intelligent club power along with futuristic darkness to make his brand of sci-fi-esque electro music called electrocore. <br /><br />Jackal and Hyde live shows are eclectic full frontal sonic assaults which appeal to a wide variety of fans from EDM club kids, ravers and break dancers, to goths, gravers and industrial heads alike. For the last decade he has played shows with a wide variety of groups from The Prodigy, Bassnectar and Stanton Warriors, to Rabbit in the Moon, Combichrist and Kraftwerk (Karl Bartos) at venues all across the United States and abroad. Always be prepared for an Earth shaking set from this master of tear out electro.


#####################################
#############  Features  ############
#####################################
features-title: Features
features-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante.

#
# Features
#
features:

# Feature
- title: Clean & Unique Design
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-vector

# Feature
- title: Professional Support
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-help2

# Feature
- title: Pixel Perfect
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-airplay


#####################################
############  Portfolio  ############
#####################################
portfolio-title: Buy Music
portfolio-description: Maecenas tempus nec mi et placerat. Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis.

#
# Portfolio Grid
#
portfolio-categories: [Electro, Electro-core, Hardcore, Breaks, Synthwave]
portfolio:

# Portfolio Item
- title: <span class="thin">COGITO ERGO SUM</span>
  categories: [Electro]
  image: img-01.png
  url: 'https://jackalandhyde.bandcamp.com/track/cogito-ergo-sum'

# Portfolio Item
- title: <span class="thin">Carl Finlow - Anomoly</span> (Jackal and Hyde Remix)
  categories: [Electro]
  image: img-02.png
  url: '#'

# Portfolio Item
- title: <span class="thin">See Europa</span> Style
  categories: [Graphic Design, Logo, Photography]
  image: img-03.jpg
  url: '#'

# Portfolio Item
- title: <span class="thin">Anywhere in the Galaxy</span>
  categories: [Websites, Video, Photography]
  image: img-04.jpg
  url: '#'

# Portfolio Item
- title: <span class="thin">Electromagnetic E.P.</span>
  categories: [Development, Logo]
  image: img-05.jpg
  url: '#'

# Portfolio Item
- title: <span class="thin">Super Meng</span>
  categories: [Development, Video]
  image: img-06.jpg
  url: '#'

# Portfolio Item
- title: <span class="thin">Sound of Underground</span> (Remaster)
  categories: [Websites, Graphic Design]
  image: img-07.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">You're Like A Drug</span>
  categories: [Websites , Video]
  image: img-08.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Photography, Logo]
  image: img-09.jpg
  url: '#'


#####################################
##########  Core Features  ##########
#####################################
core-title: Social Media
core-description: Follow Jackal and Hyde on social media.

#
# Core Features Left
#
core-features-left:

# Feature
- name: Bandcamp
  description: Buy Jackal and Hyde Music.
  icon: pe-7s-light
  url: https://jackalandhyde.bandcamp.com

# Feature
- name: Discogs
  description: View the discography.
  icon: pe-7s-drop
  url: https://www.discogs.com/artist/35393-Scott-Weiser?filter_anv=0&type=Credits

# Feature
- name: Instagram
  description: Stay up to date on Instagram.
  icon: pe-7s-coffee
  url: https://www.instagram.com/jackalandhydemusic/

# Feature
- name: Facebook
  description: Follow Jackal and Hyde on Facebook.
  icon: pe-7s-smile
  url: https://www.facebook.com/jackalandhyde/?ref=br_rs

#
# Core Features Right
#
core-features-right:

# Feature
- name: Bands In Town
  description: Follow live performances.
  icon: pe-7s-wine
  url: https://www.bandsintown.com/a/15379169-jackal-and-hyde

# Feature
- name: Mailing List
  description: Sign up for the Jackal and Hyde email list.
  icon: pe-7s-monitor
  url: mailto:info@jackalandhydemusic.com

# Feature
- name: Spotify
  description: Stream Jackal and Hyde Music.
  icon: pe-7s-crop
  url: https://open.spotify.com/artist/4a3Z4srAHtEhr1aEdB1SAi

# Feature
- name: Beatport
  description: Purchase Jackal and Hyde music on Beatport.
  icon: pe-7s-camera
  url:


#####################################
########### Testimonials ############
#####################################
testimonials-title: Notable Quotes
testimonials-description:

#
# Testimonials
#
testimonials:

# Client
- name: Zardonic
  url: https://zardonic.net/
  url-text: Zardonic.net
  avatar: avatar-01.jpg
  cite: "Beautifully well crafted electro. Dark like no other in the electronic scene today."
  logo-img:

# Client
- name: DJ Qbert
  url: https://www.facebook.com/skratchdjqbert/
  url-text: DJ Qbert Facebook
  avatar: avatar-02.jpg
  cite: "Love Jackal and Hyde! I played his new track on our Turntable TV Livestream and a guy jumped up in front of the camera and tore it up popping and locking! Everyone went haywire! Jackal & Hyde is the best!"
  logo-img:

# Client
- name: DJ Icey
  url: https://www.djicey.com/
  url-text: djicey.com/
  avatar: avatar-03.jpg
  cite: "What Wiwek is to Jungle Terror, Jackal & Hyde is to electro terror! Dark brooding bass music delivered from another solar system."
  logo-img: videohive.png

# Client
- name: Omar Santana
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-04.jpg
  cite: "The King of hard electro-core is back with a devastating and powerful bass track. Jackal and Hyde has proven once again that he is the undisputed king of this genre. This track will definitely cause a ruckus! Great work!"
  logo-img: audiojungle.png

# Client
- name: AK1200
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-05.jpg
  cite:  "If you really want to know what electro music is, go check out the new Jackal and Hyde. This is the music that shaped an era, and was instrumental in the success of breakdancing and dance battles throughout the world. If this is the future of proper electro, I can't wait to see what comes of it. Jackal and Hyde is again leading the way for electro and a revolution seems imminent."
  logo-img: audiojungle.png

# Client
- name: Dave Clarke
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-06.jpg
  cite: "The biggest f***ing bass you are ever going to experience."
  logo-img: audiojungle.png

# Client
- name: John B
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-07.jpg
  cite: This new Jackal and Hyde wax gets my RobotroniK seal of approval!
  logo-img: audiojungle.png

# Client
- name: Egyptian Lover
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-08.jpg
  cite: That new Jackal & Hyde song Bad Robot? Yea, the World must cop that… The World must cop the Bad Robot!”
  logo-img: audiojungle.png

#####################################
############# Our Blog ##############
#####################################
blog-title: News
blog-description: Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.


#####################################
############### Team ################
#####################################
team-title: Sponsors
team-description: Please support our sponsors.

#
# Team Members
#
team:

# Team Member
- name: Drone
  tagline: Artist
  avatar: avatar-01.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Goldbaby
  tagline: Audio Mastermind
  avatar: avatar-02.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Shady Teez
  tagline: Hacker
  avatar: avatar-04.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'



#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Patreon Community
pricing-description: Help support Jackal and Hyde through Patreon. The Jackal and Hyde Patreon community gives fans, fellow producers and music students a place to connect with both each other and Scott Weiser.

#
# Plan Personal
#
plan-personal-price: $5
plan-personal-offer-1-title: V.I.P. Music Aficianado
plan-personal-offer-1-info: Access to pre-releases of Jackal and Hyde music, blog posts, community discussions, behind the scenes photos, one bandcamp code per month and one autographed Jackal and Hyde t-shirt after six months of subscription.
plan-personal-offer-2-title: 100 Support Tickets
plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-url: '#'

#
# Plan Business
#
plan-business-price: $499
plan-business-offer-1-title: All the the benefits of V.I.P Music Aficiando tier plus
plan-business-offer-1-info: access to all of production blog posts that contain expert production knowledge and tutorials. Perfect for all levels of music production. Patron-only newsletter One digital downloads per month - Jackal and Hyde Bandcamp codePatron-only Q&As Access to drafts and works-in-progress Complete post archive - News and Music Production Exclusive content Live chat 15% off all Bandcamp tracks Private community Work-in-progress updates (digital)
plan-business-offer-2-title: 1000 Support Tickets
plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-url: '#'

#
# Plan Ultimate
#
plan-ultimate-price: $999
plan-ultimate-offer-1-title: 10 PSD Pack
plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-offer-2-title: Support Unlimited
plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-url: '#'


#####################################
############   Contact   ############
#####################################
contact-title: Contact
contact-description: Have a question about something or just want to say hello? Send an email through the form below.


#####################################
#############   Footer   ############
#####################################
footer-description: Jackal and Hyde Music is brought to you by Jackal and Hyde and Equinox Multimedia
footer-copyright-text: Equinox Multimedia
footer-copyright-url: http://www.equinoxmultimedia.com
footer-copyright-year: 2021
